### ISSUE TITLE
Design.Uploadertool first sketches

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#1]
[migrated here from https://github.com/Paratii-Video/paratii-player/issues/371]

Hey guys,
I have designed the first sketches for the uploader tool
I know that there are a lot of steps missing but I think it's a good idea to share the kick-off with u. I'm focusing not only on the user editing the video settings but also in how he is supposed to edit multiple videos at the same time.  (  if he needs to upload the videos that he already got from youtube and want to change the title, or just upload multiple files at once )

tell me what u think about it

![web 1920 6](https://user-images.githubusercontent.com/30123644/33695442-8b72908c-dae4-11e7-9e6e-4bdf4c7bab53.png)
![web 1920 7](https://user-images.githubusercontent.com/30123644/33695446-8f2972e0-dae4-11e7-8570-dfe68b05f6d0.png)
![web 1920 9](https://user-images.githubusercontent.com/30123644/33695450-9238a65e-dae4-11e7-9e8f-f1ff87628f72.png)

the main idea is that there are two boxes, one containing the files names where the user can select the video that he wants to edit or remove it if he doesn't wanna upload it anymore. And another that has all the options to edit the video as the user wants

**Comment by jellegerbrandy** [comment]
Moved to wiki: https://github.com/Paratii-Video/paratii-portal/wiki/Portal-Design:-Upload-Tool:-First-Sketches

**Comment by pedrocasa** [comment]
I re-open this issue because I'm trying to use the same UX of this uploader on the portal

some pictures
![up_01 2](https://user-images.githubusercontent.com/30123644/35065551-b2af98ac-fbb4-11e7-8814-66d80ce620a9.png)
![up_01 3](https://user-images.githubusercontent.com/30123644/35065552-b2cc5708-fbb4-11e7-9d3c-e6fc8c506ece.png)
![up_01 9](https://user-images.githubusercontent.com/30123644/35065553-b2e90db2-fbb4-11e7-8921-13dfa34e7e2a.png)
![up_01 10](https://user-images.githubusercontent.com/30123644/35065555-b3083980-fbb4-11e7-9689-3ed64069498c.png)
