### ISSUE TITLE
use `standard` linting

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#12]
Configure the linter to enforce the `standard` style

(currently does not: we have lots of lines ending with `;`)

**Comment by bent0b0x** [comment]
@jellegerbrandy semi-colons are required because of the `prettier` formatting rules; right now those are overriding all `standard` formatting rules (although non-formatting-related `standard` rules should still be enforced). 

My two cents is that we should let go of our code-formatting predispositions and just let prettier handle it, so we can worry about other things (encapsulated very well in this tweet)
![image](https://user-images.githubusercontent.com/7697924/34319737-84394ff6-e7b7-11e7-8de0-962cd028cc05.png)
https://twitter.com/jkkramer/status/889565403738976256

However, we can change this and enforce all `standard` rules if we want. The downside would be that the prettier output alone would no longer pass our build process. Let me know what you think!

**Comment by jellegerbrandy** [comment]
Oh no, @bent0b0x , you have started a style war :smile: 

I vote for going back to have `standard` as the basic: it is what we use for `paratii-lib` and `paratii-player`: it is better to be consistent, and we all have our IDE's configured for that (as well as our brains, or at least mine :-)

**Comment by bent0b0x** [comment]
Haha oh no!

Gotcha; I just found https://github.com/sheerun/prettier-standard, which looks like a prettier formatter that adheres to the `standard` rules. I'll test this out today and look at swapping in for regular `prettier`. 

Or, just let me know if you think it is best to ditch an auto-formatter altogether. I personally really like using them but open to a different viewpoint.

**Comment by jellegerbrandy** [comment]
I am very much in favor of code standards, and I agree completely with the tweet you cited: that is more important to have a fixed style, but that the detaisl of that style are mostly abritrary : that is why I think we should not change them :-)

**Comment by jellegerbrandy** [comment]
Anyway, closing this as it seems to me perfect now :-)
