### ISSUE TITLE
write content for the guide component

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#133]
I.e. some text to put in the component developed here: https://github.com/Paratii-Video/paratii-portal/issues/119

**Comment by felipegaucho** [comment]
1) **PTI is the native token of the Paratii open system. We call it a "system" because the network executes operations with PTIs although nobody "owns” the machinery who does the job.**
PTI tokens are issued, distributed and collected by smart contracts that live on the Ethereum blockchain. Every new registered user on Paratii earns some tokens to experiment with. They show up on the top right of this page (click that icon!) or in our embedded player, when one is watching through other sites. Let’s see what you can do with PTIs?

2) **The basic operation here is *staking*. Whenever you upload a video, 5 of your tokens will be automatically "attached to it”, as it enters the system. Think of it as a security deposit.**
At any time, you will be able to retrieve your tokens back, which also delists the video from this web portal and related interfaces. On the other hand, those who leave tokens staked are continuously granted rewards, issued through inflation, and can also earn profits if the playlists their videos belong to are performing well (these two functions are not live yet). So uploading content and staking are forms of active participation in this economy.

3) **Videos will be subject to “flags” _(maybe even use the icon of a flag, small, within the text, @pedrocasa?)_. Flagging a video means matching its stake, by putting up an equivalent amount for challenge.**
Any user can then go in favour or disfavour that video’s presence on the system. Videos collectively rejected lose their stakes - forfeited PTIs go to voters in the challenge (people who flagged or disapproved) and to all people actively staking tokens in the system, at the moment. That means that keeping a well curated record of videos - one that keeps attracting creators and spitting out harmful content - can be a profitable activity to the system's participants.

4) **Soon, PTIs will also be usable for facilitating micro payments. Creators will have monetisation options to directly receive value from their audiences and/or advertisers**.
Most important for now is that you understand PTIs as an entry ticket to take part in an economy that belongs to you as much as you are willing to belong to it. Tokens displayed here are in a test environment still, and have no monetary value. If you're willing to claim some extra test PTIs, ask questions, or make suggestions about the token's feature set itself, don't hesitate to [get in touch](mailto:we@paratii.video).

**Comment by jellegerbrandy** [comment]
Great. @jrgarou , can you insert the texts in the component you wrote?

**Comment by jrgarou** [comment]
PR for PTI Guide https://github.com/Paratii-Video/paratii-portal/pull/169
