### ISSUE TITLE
If you have 0 balance, the staking modal should tell you this

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#229]
Now it just fails silently if you click "stake"

**Comment by felipegaucho** [comment]
Can we have a loading (3 dots?) that replaces the "continue" button after you click it? 

Having it can be useful regardlessly, since the action usually takes 2-5s to complete. 

Then the modal simply goes away, **if all went right**; and the dots become a "Failed", grey or red, non-actionable/non-activated button". Remaining actions, then, are: close modal; or click on "ask for more PTI", on the text.
