### ISSUE TITLE
Save vs Publish

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#266]
At the moment, the user cannot save the information he is adding until transcoding is finished (which may take long time), because ethe "publish" button is disabled. 

Proposal:
-  1 while transcoding is in progress, the button says "Save" and saves the info on the edit form. Perhaps, after the user clicked "save", we can tell her that she needs to wait until transcoding is finished before she can publish the video.
- 2 when transcoding is done, this changes in "Publish". Clicking on this will save the information, and then open the staking modal.
- 3  After the user has published the video, the button changes to "Save" again.

**Comment by pedrocasa** [comment]
I'm going to use numbers to help us to talk about each topic

1-2  This can get a bit confuse ... Probably some user may click on the save button and just leave the page after the action because we are not showing the buttons at once ( there's no way to know that this action is gonna change to "publish" later)

- possible solution to it 

The only reason to have a "save" button is for users who don't want to publish it right now ( maybe because they don't have enough money or because it's no the right time to do it) am I right?
What if we have something like this ?

![group 455](https://user-images.githubusercontent.com/30123644/36733972-f3ab8aac-1bb0-11e8-8d67-1b5188908aa5.png)

**Comment by jellegerbrandy** [comment]
* There are 3 reasons to have a save button:
  - cannot publish now because transocding is not done yet
  - do not want to publish now because of 0 money or whatever
  - is already published

I agree though that one button is confusing.  I'd rather have "Save"  and "Publish" next to eachother (not in different parts of the form).

**Comment by pedrocasa** [comment]
![box_edit](https://user-images.githubusercontent.com/30123644/36746539-5670b08e-1bd1-11e8-9777-ffc16725ab29.png)
