### ISSUE TITLE
Safari - portal is not working

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-portal#342]
Error stack:

<img width="378" alt="screen shot 2018-03-13 at 12 23 06 pm" src="https://user-images.githubusercontent.com/26517120/37351224-595f899e-26b9-11e8-9e75-4d0cf9c658ac.png">

Maybe is related to https://github.com/mishoo/UglifyJS2/issues/1753

**Comment by bent0b0x** [comment]
[This] may be the fix

**Comment by bent0b0x** [comment]
@eliawk @geckoslair @jellegerbrandy do any of you know of a computer w/ Safari 10 installed? It is not easy to download old safari versions and I have `11` installed.

If you do, ` 342-safari-10-fix` is the branch w/ a potential fix.

**Comment by eliawk** [comment]
@bent0b0x we have tried w/ Felipe's Safari 10 - now we get another error in console:
`can't find variable createUtil` and the portal doesn't start

**Comment by bent0b0x** [comment]
This also affects Safari 11

**Comment by bent0b0x** [comment]
Okay, so I figured out a way to test on Safari 10. However, the portal works just fine locally on safari 10, whether I build in dev mode, staging mode, or production mode. The fact that staging and production do not work leads me to believe that we have a problem in our deployment build process. @jellegerbrandy can you provide me access to the `devops` repo so that I can inspect our deployment scripts?

**Comment by bent0b0x** [comment]
This is now resolved on staging

**Comment by bent0b0x** [comment]
One thing I did notice. The server from which we deploy uses a different node version than we use on circleCI and locally. This could potentially cause issues in our build process. @jellegerbrandy @Leeaandrob is it possible for us to build the app on circle and then upload the build output to its destination? I think this could be good because we configure our build env via the circle config, but AFAICT this isn't used at all when we actually build the app before deploying it. 

Thoughts?
