### ISSUE TITLE
it is unclear how to copy the 12 words

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#499]
I see  that you can click to copy, but it seems to me that we do not need to invent new ways of copy-pasting here. They should be selectable (as well).

**Comment by pedrocasa** [comment]
There are two ways to solve it

Create a copy button as we did in the past
-
![screen shot 2018-04-26 at 12 05 38 pm](https://user-images.githubusercontent.com/30123644/39314230-2a5d523a-494a-11e8-9804-31ad6b879ecb.png)

Good points of it 
- Still using the number boxes can show the 12 words in a very explicit way, it clear what the order is and it's easier to copy find each word if you are writing it down in a piece of paper

Bad points of it
- It brings one more element to the layout. We already have the word boxes, the checkbox and now and now we are adding a button to copy it


Not using the word boxes 
-

![image](https://user-images.githubusercontent.com/30123644/39313702-0580314a-4949-11e8-9c73-d0340bbcd615.png)

Good points of it
- Easier to copy and paste because it's a text line and the user will probably think that works in the same way as every text line on the internet ( he would think it's copiable)

**Comment by jellegerbrandy** [comment]
In spanckchain (I think) you the words are shown in boxes, but you can just select them with your mouse. I.e. it behaves like normal text.

**Comment by pedrocasa** [comment]
well,
I was mistaken about the good point of the first picture. I've made some real tests here at Bossa Nova to see how people would copy it on a piece of paper and the result was not what I was expecting. 

![screen shot 2018-04-26 at 3 14 29 pm](https://user-images.githubusercontent.com/30123644/39324020-c3eaa9f6-4964-11e8-80a4-f3b67765b6c9.png)

- People took twice the time to copy the 12 words in the first scenario.
-  There are some people (including one that already knows a lot about crypto) that copied the 12 words like this ( image below). This is terrible because they may try to enter on their account using a completely wrong word order

![image](https://user-images.githubusercontent.com/30123644/39323462-12740ea2-4963-11e8-9b31-8ae6451d665a.png)

I do think that we should use a layout like this (image below). I'm not a big fan of how it looks in comparison to the word-box layout, but it's the best choice in the usability matter

**Comment by jrgarou** [comment]
Nice, @pedrocasa 

A copy button would be quite user-friendly.

![image](https://user-images.githubusercontent.com/320157/39326354-15ddb2a2-496b-11e8-806c-33b3f3502fb0.png)

**Comment by pedrocasa** [comment]
![screen shot 2018-04-26 at 4 50 55 pm](https://user-images.githubusercontent.com/30123644/39328529-02441fcc-4972-11e8-831a-22285152f2bd.png)

**Comment by felipegaucho** [comment]
@pedrocasa @jrgarou what do you think of something more like this:

![frase](https://user-images.githubusercontent.com/26517120/39387322-57ab68a2-4a4f-11e8-8424-b57c3e5952cc.jpg)

Don't want to be too picky, but this is probably the single most important piece of information to keep, of all the things, so it should probably not be in discreet left-aligned lower case as if it was any other text.

**Comment by bent0b0x** [comment]
I think we must call out this fact: without this key you cannot possibly ever log in to this account on another device (right). 

Without understanding this I don’t think most users would care about a recovery key, as for all other apps if you know your username and password you can log in. I think it will be a challenge to shift users away from this type of thinking

**Comment by jrgarou** [comment]
(continue with the @bent0b0x  "anarchy" comments 😄)
Do you think that just `Rewrite your account recovery phrase` to recover the password is enough?

**Comment by jrgarou** [comment]
@felipegaucho good!
the _bold words_ is done in this PR https://github.com/Paratii-Video/paratii-portal/pull/511
