### ISSUE TITLE
Investigate react SSR for SEO/embeds

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#50]
Currently, the entire app is rendered client-side. To fully support google/search engine web crawlers, and have our pages/embeds appropriately scraped, we likely have to support server-side rendering as well. This is an issue to track a high-level investigation into this question.

**Comment by jellegerbrandy** [comment]
This is a good point, but I would phrase it differently, because there are also other types of solutions.

For sharing (oembed) and for web crawlers that do not support javascript, we need to service different pages at URLs like `play/someVideo`. In particular, we need to set headers specifically for the video, and show some content specifically for that video.

Note that this issue is only relevant for non-javascript enabled clients (<-- I'm not 100% sure about this).

There are (I think) two types of solutions here:

1) Server side rendering
2) Create a separate middleware (at the Apache/nginx level) that sets the appropriate headers

SSR of course also has optimization benefits, and gives us more control over what info we serve. 

@enricocicconi : what do you thing?

**Comment by jellegerbrandy** [comment]
closing this as it is already discusse din #55 and tracked in PR  #57
