### ISSUE TITLE
Create 2 webpack.configs for dev and production

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#51]
https://webpack.js.org/guides/production/

webpack.common.js
webpack.dev.js
webpack.prod.js

**Comment by bent0b0x** [comment]
@eliawk can you detail what the ultimate need is for this change?

**Comment by jellegerbrandy** [comment]
@bent0b0x , the use case is as follows. to functino, the portal needs to know the addresses of the contracts on the blockchain. This all passes thorugh a registry contract that contains the address of the other deployed contracts. This registry address is more or less stable in production (currently it is 0x0B101ff870F8BAd6c437C45eCb2964D7e8034593), but will be different for the staging server (not there yet) and will be a new fresh address when testing. 

So, thinking about it, we perhaps do not need the `webpack.dev.js` variant (since the tests are not running against the webpack'ed code, but against the es8 code directly), but we will need a `webpack.prod.js` and (in the near future) a  `webpack.staging.js`

**Comment by bent0b0x** [comment]
I'm not sure we will need separate _webpack_ configs for this, but rather just regular json config files w/ these kinds of settings. And we could import those config files conditionally based on the `NODE_ENV`, into our `webpack.config.js` and use the `WebpackDefinePlugin` to set them in our code

**Comment by jellegerbrandy** [comment]
I'm not sure why that would be better/simpler though than having 2 different files

**Comment by bent0b0x** [comment]
My reasoning is this: the webpack configs are primarily for defining our build process, and possibly secondarily for injecting variables into our code (at least that is how I view it). To avoid confusion on the build process and to ensure the build processes in different environments does not diverge too much, I would like to keep that all in one file. For things that need to diverge based on env, like what we are talking about here, then separate config files makes sense, but our webpack config can just `require` those conditionally. 

I’m speaking from some experience here where I worked on a project with a prod webpack config and one for dev, and it made it very easy to add something for dev and forget to do it for prod.

All of that said, willing to look at a PR with this implemented and eat my words later on!

**Comment by jellegerbrandy** [comment]
sounds good to me
