### ISSUE TITLE
Implement 1st simple profile page

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#528]
These could be the first 3 iterations for creating the profile page:

## 1. Superbasic profile
https://github.com/Paratii-Video/paratii-portal/issues/528#issuecomment-386326606

As a part of this page: https://staging.paratii.video/wallet, i.e. on the page you see when clicking on the avatar.

### 2. Superbasic profile + options
Put the superbasic profile card in the top left corner, add the options on the menu below (still all locked). We can put the videos of the account on the empty right side, still in the ugliest/simplest form possible.
Separate issue (dependant on this one): 

### 3. Differentiate between liquid PTI / staked PTI

Transform the "balance", under the username, into the divided liquid / staked balance viewer that @pedrocasa has designed:
Separate issue:

### 4. Migrate current "upload" list to new profile page

Migrate what we currently see on https://staging.paratii.video/upload to the  "My videos" list on the new profile page (and remove the old page).  This step is mostly moving stuff around, UI, no new functinality  (still using the TCR placeholder). Also, @pedrocasa suggests we have a "cover image" here. I suggest we begin with some randomly generated stuff.

### Next steps

Next steps we will define when we get there (informed by what we learned in the previous steps), but they will include:

* Statistics about video (when uploaded, popularity, stuff like that)
* TCR challenge information about your videos (which of my vids is cahllenged? Which are fine?)
* TCR active particpation (i.e. discovery, challenging, voting)
* Transaction history
* Playlists (?)

**Comment by pedrocasa** [comment]
Layouts for the V.0.1 of the Profile page

 ( not many features /// working with what we already have got) 

![web 1920 14](https://user-images.githubusercontent.com/30123644/39584711-6def63ce-4ec9-11e8-8f72-2bac4d766805.png)


Card to edit the information 

 
![web 1920 15](https://user-images.githubusercontent.com/30123644/39584747-8ffdff66-4ec9-11e8-886c-aeb7a997f058.png)

The main reason for doing two different places for editing the information (as Jelle suggested) is because we are not going to have only changeable information but also pieces of information that are not gonna alternate if the user clicks on the submit button. (balance, address)

**Comment by eliawk** [comment]
@pedrocasa form me it's good - i think me or @jrgarou we can do it, or both

**Comment by felipegaucho** [comment]
Closing this since step #1 is done @eliawk  @jrgarou 🙏 
Keeping track on progress here: https://github.com/Paratii-Video/paratii-portal/issues/587
