### ISSUE TITLE
Create "VIDEO IN THE TCR page"

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#560]
Time for some iterative planning. The issue will be closed when we move to step 2, we'll open a new one w/ the rest, close it when moving to step 3, and so forth. We'll start off thinking about 3 modules: **(A) the "video in the TCR page"** (where you see its stats, metadata, current status, and time-counter/challenge-vote options); the **(B) "list page"** (listing items and allowing filtering, like, per status); the **(C) "dashboard page"** (your stats, reminders, earnings overlook, precise state of your tokens - including, in the future, if you have stuff delegated to you).

For now, we can think that general "propose-challenge-derived" information about your videos, if you are a creator, will remain in your "my videos" page, or critical stuff will be notified to you - outside the TCR "special area".

Basic considerations: 
- **In principle**, we're thinking the curation screens as subdivisions of **a tab under the user section**, that brings up 3 "sub-tabs", as per the modules above. We can split the whole interface off to a different URL at any time.
- The basic wallet info. we'll soon have, on the top left (above this menu), can be "reused" to show users basic information on PTI available and staked, in the TCR screens (this can save some space in the "dashboard").

## 1. Create "VIDEO IN THE TCR page"
Equivalent to [THIS PAGE](https://publisher.adchain.com/domains/la.com). Our rough pen sketch is [HERE](https://imgur.com/FhsHVQ1). Video thumb, name, date, author, proof of ownsership (emphasis!) // "Status box" with current status (see item 3 for **the exact words to use**), option to challenge (or time counter + option to chosse side of vote, if in commit phase; or time counter + place to reveal vote, if in reveal phase). Note that the **costs** to challenge or vote will be visible in the buttons themselves. For now, we won't have flexibility as for voting with multiple tokens (only standard values).
This box has a lot of states. We outlined most of them [HERE](https://imgur.com/a/uI4fGaN). @pedrocasa, make sure to refer to the AdChain Registry "Help" section for the most precise UX explanations.
We'll have no stage map (never, in principle) or field for discussions (just not yet).

### 2. ADD a "CURATION" tab in the "user area"
Just a new option on the vertical menu that will open up this world. On the right side (the empty screen), it'll have **only** an ugly, raw field where you can input a videoID and press enter. If the videoID exists, you'll be redirected to its "video in the TCR page" (the screen we drew above, in #1 🎉 ).

### 3. Create LIST PAGE
Akin to AdChain's main page, **a list** where the freshest videos come up, with their: **name, magnifying glass icon (a link to go to the "video in the TCR page"), stage, action to be taken, time missing for this "stage" to finish (if it applies)**.
A **filter**, with: **whitelisted; challenged (in commit); voted on (in reveal); rejected.**
A **search box**, that simply modifies the content shown in the list.

### 4. Create DASHBOARD
Still to be defined. We'll probably have: Total Times Challenged; Total Times Committed; Total Times Revealed; Total PTI Claimed.
Instead of boxes for specific stages, below, I think we should have a generic box for stuff going on (like a list, that shows for each item what you've done to it), space for notifications and more expressive stats. @pedrocasa please ping us when we get to this step.

### 5. Add "DISCUSSION BOX" to "Video in the TCR page"
Like AdChain does with reddit, in a way that emphasizes our proof-of-ownership.

### 6. Have a tab/suboption called GUIDE
Where we can borrow helpers inspired by the ones already used around, in our references.

## Next steps
💭Write your concerns here...

**Comment by jellegerbrandy** [comment]
just to be clear, the "video in TCR" page is a separate page, or we are talking about a card to add to the video page?

**Comment by pedrocasa** [comment]
It's a separate page. We want to separate the curatorship as much as we can to the regular portal

**Comment by pedrocasa** [comment]
The first designs of the VIDEO IN THE TCR page.

![000](https://user-images.githubusercontent.com/30123644/39927132-acbadcd4-5507-11e8-949e-edb9031afb98.png)


The pages on the link are not in the regular order because I designed some layouts for specific situations (ie. What would happen if the user clicks on a video that is "on reveal period" and he did not commit any vote in the past). 

https://xd.adobe.com/view/73170ee2-d4de-46bf-b97f-29f00d90263b

- UX  - I tried to follow the logic behind the https://publisher.adchain.com/ if some small changes.  (for example, using the LocalStorage to save instead of the ID [as @ya7ya  said]

- UI - I tried to make the elements modular as possible in order to edit/change things in the future ( there are a lot of empty space/modular boxes that can be used for other features)

https://xd.adobe.com/view/73170ee2-d4de-46bf-b97f-29f00d90263b

[front-end] there are some pages called "proof of responsiveness" (sorry for the name🙈) to show how the breaking points would behave in 1440 and 1680 screens ( I will get on mobile soon).

There are some points that we can still improve (such as give more contrast between the proof-of-ownership and the rest of information) and I'm open to any suggestions.

**Comment by jrgarou** [comment]
The _.xd_ file https://www.dropbox.com/home/paratii-design/master?preview=paratii-tcr-videopage.xd

**Comment by pedrocasa** [comment]
If anyone besides @jrgarou  wants the access to the dropbox link (XD FILES) above please just ask me

**Comment by jellegerbrandy** [comment]
closing this as it is not actionable
