### ISSUE TITLE
Add avatar and username on the login process

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#574]
We should add the avatar, user nickname, and a button to use a different account on the modals that ask for the user's password 

https://xd.adobe.com/view/82eb6350-c8dc-459c-9941-4a8af2f2b60f

**Comment by felipegaucho** [comment]
Nice catch, @pedrocasa, makes things much more familiar.

If @jrgarou , @eliawk or @bent0b0x would like to take this one, let us know - and un-assign the rest :)

2 things:
- I vote for **eliminating the subtitle** ("Please insert your password...")
- Also, as Jr. has done elsewhere, I vote for **using only "Since 2018"**, instead of "Paratii member since 2018".

**Comment by bent0b0x** [comment]
I'll take this one
