### ISSUE TITLE
[discussion] we need integration tests! 

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#647]
Thanks to @bent0b0x , our chimp-tests do not run against paratii-db anymore, because these responses are now all mocked

this makes our tests slightly faster and more predictable, but the fact is that we have no integration tests at all: we have no tests that check if paratii-db behaves the same way as the mocks are defined

(An additional complication is that we are now mocking paratii-db in both paratii-js and paratii-portal (and not very systematically, at that), which makes it harder to accomate api changes)

Here are some things we could do (not mutitally exclusive):

* Revert the mocks in paratii-portal, and test against a paratii-db instance. (The idea being that the chimp-tests are meant to be integration tests). 
* Write separate integration tests (in paratii-portal and paratii-js)
* Factor out the mocks (so at least we have a consistent code base); ideally, they should be a (sub)package of paratii-db (so logic and changes in the logic remain in the same place)

**Comment by bent0b0x** [comment]
I think reverting the mocks is good if we can write some scripts that will do the following:

```
- provision a new mongo db
- seed the db with all of the user, video, etc data we need
- ensure portal connects to this db
- delete the db once the tests are complete
```

All of this while maintaining whatever db we use for local development.

Also we may want to include `paratii-db` in `devDependencies` of `paratii-portal`, so that whenever you install `paratii-portal` you get the db for free (which is good since it would be required to run tests).

**Comment by jellegerbrandy** [comment]
working on this in #681 (feel free to contribute)
