### ISSUE TITLE
Better precision (for high values) in showing credits on current sidebar

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#764]
Current if we got a value higher than XXX the systen adds a "K" after it. We should be more precise and show as much as we can . In order to have more space let's remove the "PTI" that's writter side by the numbers.

![image 1](https://user-images.githubusercontent.com/30123644/42292999-0fa06542-7fad-11e8-8e6a-9c346cff71df.png)

The space of the boxes is not enough to fit any value (be it fractional or integer value). and probably when the users enter with ral high values these boxes will not be enough to see the complete balance.

- What can we do to solve this? We can show as much as possible in these boxes (when it does not fit everything we can add "..." after the numbers) and show the value completely in a page that is directly related to money (in our case "finances page").

![screen shot 2018-07-04 at 5 14 25 pm](https://user-images.githubusercontent.com/30123644/42293085-bc4206a2-7fad-11e8-9f20-c33b7c5272ef.png)

Showing the available PTI values and PTI staked one on top of the other could be an option but that would kill our percentage bar down

**Comment by jellegerbrandy** [comment]
Maybe we can do it like this: we define a maximum number of characters, say 10, and a precision, say 3 numbers behind the dot. And then we can do that if the number is more less than 10 chars, we print it completely, and if it is more, we use the abbreviation. So it would be something like this:

1 --> 1
1234567890  -> 1234567890
12345678901 -> 12345M
12.234 -> 12.234
12345678.901 -> 12M

(see what I mean?)

**Comment by pedrocasa** [comment]
Yes, Thnks a lot Jelle

**Comment by bent0b0x** [comment]
>1234567890 -> 1234567890
>12345678.901 -> 12M

The first number is bigger than the second and yet we show more precision for it. This doesn't really make sense to me.

How about we determine the precision by the number of digits before any decimals (i.e. max 10, any more we go to `M` for million, etc)

**Comment by bent0b0x** [comment]
@pedrocasa @jellegerbrandy actually, can we talk about this? I'm not sure I really understand what the problem is. We already are using a system where we show a certain number of digits and after a certain value we show abbreviations. 

What problems is this causing on the pages where we already are already showing PTI?

**Comment by jellegerbrandy** [comment]
The problem with the current system is that 10.000 and 9.995 are both
represented as "10K". That means that there is no place where you can see
that you have paid 5 PTI.

so that is not good.

What I am proposing is that we show as much precision as the physical space
allows. So if we have 10 chars, and the number is shorter or equal then 10
chars, we show the entire number, and if the string is longer 10 chars, we
show the abbreviated value.
This is still not perfect, but at least we show the precise number in all
cases where we can (which is better then what we have now).

>1234567890 -> 1234567890
>12345678.901 -> 12M
> The first number is bigger than the second and yet we show more precision
for it. This doesn't really make sense to me.

The first number is *shorter* than the second, though :-)

**Comment by felipegaucho** [comment]
Not valid anymore since this part of the UI got simplified :)
