### ISSUE TITLE
Embed player is using a different wallet

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#766]
I was trying to watch the embedded videos (twitter) in the same browser where my account is saved and the addresses are not the same

![screen shot 2018-07-05 at 4 40 13 pm](https://user-images.githubusercontent.com/30123644/42344250-1d5ed82e-8072-11e8-923d-d329f5d5ce71.png)

![screen shot 2018-07-05 at 4 13 27 pm](https://user-images.githubusercontent.com/30123644/42344177-deabc312-8071-11e8-84b3-a58e182e2f52.png)

I tried both staging and portal.paratii

- [ ] We need to remove the profile icon in order to don't get anyone confused

**Comment by jellegerbrandy** [comment]
Good point.
The reason is taht in the portal you are logged in, and in the embedded version you are not (and using the anon account, which is different)

This is of course confusing. Basically, in the portal, as it is now, in "anonymous mode" the address info is not accessabile via the UX; while in the embedded version it is right there under the profile button. We should make both cases behave the same: at this point, i'd say to also hide the account info in anon mode.

**Comment by bent0b0x** [comment]
☝️ I think it is indeed a bug that we are showing the account info in anon mode

**Comment by jellegerbrandy** [comment]
We can remove the profile icon from the embedded version alltogether.

**Comment by bent0b0x** [comment]
@jellegerbrandy @pedrocasa so actually, the profile icon is shown _only_ in the embedded version and this was done intentionally. We hide it in the portal version because we already have a more extensive profile/account flow there.

But, as we are discovering here, we only see data about the anonymous wallet in the embedded player, which is fairly useless. As I see it, we have at least two options:

- remove this button altogether
OR
- design and implement login/secure flow in the embedded player

Thoughts?

**Comment by jellegerbrandy** [comment]
Strongly for "remove"

**Comment by pedrocasa** [comment]
I Totally agree with Jelle
