### ISSUE TITLE
User nav needs close/dismiss button

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#771]
Right now when you open the user nav, the only way to close it is to click your avatar in the main nav again. This is very far away from the user nav and I don't think anyone will realize this is how to close it.

![image](https://user-images.githubusercontent.com/7697924/42422226-1938fc80-82b0-11e8-9ed9-197ce5109970.png)

@pedrocasa I am pretty sure the side nav needs a close button. Thoughts? If so, Is a white X fine?

**Comment by jellegerbrandy** [comment]
It definitly does need a close button, not so much because it is useful to close it, but because it covers the "conent" part in the middle. (I had assumed this was a bug and still to be fixed, is it, @pedrocasa ?)

(Personally, I'd choose a sidebar that is by default open. and usually stays open (and so should not cover the content), but which is optionally closeable.)

**Comment by pedrocasa** [comment]
Yes, it still needs to be fixed. The Sidebar is gonna stay open since the user log in 

example:

![web 1920 20](https://user-images.githubusercontent.com/30123644/42517768-e07fe6f0-8436-11e8-8ac4-1a4d3e396b9c.png)

**Comment by jellegerbrandy** [comment]
can we close this, @pedrocasa ?

**Comment by pedrocasa** [comment]
yes
