### ISSUE TITLE
show avatar for profile icon top right if the user is not registered

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#81]
i.e. instead of the nice picture of pedro :-)

when the user has registered (registration etc is still to be done), we should show the profile pic.

**Comment by mrocha94** [comment]
About profile pic, does it worth using a upload image? There is a lot of apps and sites that use gravatar instead of a "private" upload image. Thinking in a decentralized way, the best (easy?) is to use the gravatar related to user address and if there is a registered email, use the gravatar related to the email. So we don't have to store any profile pics on blockchain or ipfs - gravatar does it for us.

**Comment by jellegerbrandy** [comment]
For "normal" users (i.e. people that watch video), I agree with you that at this point, there is no real need for uplaoding images (nobody but you would see the image anyway).

However, for creators, it does make sense to uplad an image and give them a face..

**Comment by eliawk** [comment]
https://github.com/Paratii-Video/paratii-portal/pull/89
